Classes/Controller/FrontendController.php

from Slack:
> bug in the WsPreview
> 
> [16:46]  
> in typo3conf/ext/templavoilaplus/Classes/Controller/FrontendController.php:398 you pass an object "$dsObj" as parameter. the visualID function expects an array
> 
> [16:47]  
> the array is seemingly the DS record, which is not handled accordingly in the DataStorage object u pass
> 
> [16:49]  
> i guess what you want to pass is the $DS-array
passes $DS array to $this->visualID function

fixes broken workspace preview

---

Resources/Public/StyleSheet/mod1_default.css

Idea is to harmonise the design between the modules. Copying design from
TYPO3 core page module a bit and adapting colouring and spacing.
Especially removing floats and font-size declarations from old
6LTS-templavoila-CSS file.
Resolves: #60

[FEATURE] Adapt design of page module to 7LTS new backend styles

---

Classes/Controller/BackendLayoutController.php

We now support core hooks for rendering content at top and bottom of the content-editing area.
All registered hook classes to the core hooks
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['cms/layout/db_layout.php']['drawHeaderHook']     and
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['cms/layout/db_layout.php']['drawFooterHook']
will automatically render their content in the templavoilaplus page module, too.
Resolves: #79

[FEATURE] Implement drawHeaderHook/drawFooterHook from TYPO3 core in PageLayout

---

Classes/Controller/BackendLayoutController.php

This bugfix fixes the link-generation of the star-shaped bookmark/shortcut button on each page in the TemplavoilaPlus page-module.

[BUGFIX] fixes link of bookmark/shortcut button in backend module

---

Classes/Controller/FrontendController.php

Custom TypoScript constants defined in files like setup.txt via
plugin.tx_templavoilaplus_pi1.TSconst are not available in the frontend
controller, because they are not added to the $GLOBALS['TYPO3_CONF_VARS']
['FE']['defaultTypoScript_setup'] array. But are checked in
Ppi\TemplaVoilaPlus\Controller\FrontendController::processDataValues
See  https://github.com/pluspol-interactive/templavoilaplus/issues/122

Add user defined constants to TypoScript configuration array

---

Classes/Form/Container/FlexFormElementContainer.php

prevents BE flexforms of FCEs from containing empty section lines

[BUGFIX] skips rendering of flexform markup for FCE fields with eType "none" (Element Preset: Typoscript only)

---

Classes/Controller/BackendControlCenterController.php

This fixes a bug with static DS icon files causing error in backend module.
I found that in TYPO 7.6.23 if I have file /fileadmin/templates/ds/fce/myFCE.xml and /fileadmin/templates/ds/fce/myFCE.gif then I got the error:
```
Uncaught TYPO3 Exception
#1320286857: File ../fileadmin/templates/ds/fce/myFCE.gif is not valid (".." and "//" is not allowed in path).
```
This happens in Resource object / factory which expects valid htdocs - relative path.
More - it seems that $previewIcon that causes the problem defined in line 630 is not even used anywhere in code (was removed in one of revisions and forgotten).
I fixed the thumbnail generating line and added conditional displaying it in the info table.

[BUGFIX] Fix DS preview icon generating error and display

---

Configuration/TCA/tx_templavoilaplus_tmplobj.php

Fixed error `#1289918325: Module wizard_add.php is not configured.` when trying to create Data Structure via wizard.

[BUGFIX] Fixed data structure wizard name in tmplobj TCA configuration

---

Classes/Controller/BackendLayoutController.php
Classes/Service/ApiService.php

The Backend module outputs many HTML/CSS classes for content
elements according to the fields in the tt_content table (e.g.
CType, tx_templavoilaplus_tobj). Obviously the field 'layout'
should by definition have an optional impact on the output as well.
One could argue that this must not be the case and that each
arbitrary tt_content field might be relevant, however layout was
designed for this purpose in the first place. So I propose to add
this specific field to the output.
This would improve the option to style the backend module with a
custom CSS via the PageTSconfig
mod.web_txtemplavoilaplusLayout.stylesheet.myvalue  = path/to/my.css

[FEATURE] add tt_content.layout as CSS class to BEmodule output

---

Resources/Private/Language/locallang_db.xlf

`tx_templavoilaplus_datastructure`and `be_groups.tx_templavoilaplus_access` were missing the Plus in their respective TCEFORM labels

[TASK] Fix labels not always having correct extension name spelling

---

Classes/Controller/BackendLayoutController.php

create_function() is deprecated in php 7.2 and it displays notice in Page module. Changed to anonymous function.

[BUGFIX] deprecation notice in backend Page module on php 7.2

---

Classes/Controller/BackendTemplateMappingController.php

See https://github.com/TYPO3/typo3/blob/bf181a7500ada580b77f5587f25c9ed72c1a1113/typo3/sysext/core/Classes/Html/HtmlParser.php#L192
If **$splitByHeader[1]** is empty, because there isn't a header tag, an exception is thrown:
`Argument 1 passed to TYPO3\CMS\Core\Html\SimpleParser::fromString() must be of the type string, null given, called in /var/www/ekbo/vendor/typo3/cms/typo3/sysext/core/Classes/Html/HtmlParser.php on line 194`
The class **HtmlParser** was refactored in TYPO 8.7.32 ELTS and TYPO3 9.5.29 LTS. At the same time the class was designed type safe, that is why the error occurs in that case.

 @schneiel Fixed header parsing bug if head tag is not set since TYPO3 8.7.32 ELTS and TYPO3 9.5.29 LTS.

---

Classes/Utility/TemplaVoilaUtility.php

NullSite was failing as it was missing the `use` statement at the top.
This replaces NullSite with using the PseudoSiteFinder as it returns a
more robust "site" instance - as used in the core SiteMatcher class in
the `matchByPageId` method

[BUGFIX] Replace NullSite with PseudoSiteFinder

---

Classes/Controller/Backend/ControlCenter/TemplaVoilaPlus8UpdateController.php

There are two queries on tx_templavoilaplus_tmplobj and tx_templavoilaplus_datastructure that use the DeletedRestriction class to exclude soft deleted records but the TCA configuration file for those two tables has been removed in 8.0.0.

Replace DeletedRestriction with where() in update script

---

Classes/Service/DataHandling/DataHandler.php

If content is created in LIST module there was an algorithm
that tried to detect the correct CE-field in the TV+ datastructure.
However this does not work anymore and should be fixed.

[BUGFIX] if new content is created in LIST module it is not linked

---

Classes/Service/ApiService.php

Creating a record via wizard should create record and then edit it, however if the creation of the record fails because tt_content was extended sloppy (wrong default values, required fields which are not set), this creation fails and the edit will throw the wrong exception `$uid must be positive integer, 0 given` because not uid was returned.
This patch throws the exception early and thus allows to find the error more easy

[BUGFIX] if create record wizard fails this is catched silently instead of handled

---

Classes/Utility/TemplaVoilaUtility.php

TemplaVoilaUtility::getUseableLanguages() tries to get the languages for the BackendModule. If the sites are not positioned on the site root, but deeper, there are tree nodes without sites. TVP used PseudoSiteFinder for those cases, however 10LTS dropped it.
In core the solution is to use a NullSite, e.g. https://api.typo3.org/10.4/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_routing_1_1_site_matcher.html#a6821b949a0dc9742279e6c0339ceaa78
Same proposed here.

[TASK] PseudoSiteFinder not available in 10LTS

---

Classes/Handler/LoadSave/YamlLoadSaveHandler.php

The `\SplFileInfo::getPathname()` function returns a backslash between the folder path and file name on Windows and the TYPO3 YamlFileLoader class calls `GeneralUtility::getFileAbsFileName($filename)` which returns '' if there is a backslash in the path (verified in `GeneralUtility::validPathStr($filename)`).

Fix TYPO3\CMS\Core\Configuration\Loader\Exception\YamlFileLoadingException when loading mappings on Windows

---

Resources/Private/Language/Backend/PageLayout.xlf
Resources/Private/Partials/Backend/Preview/Templavoilaplus_pi1.html

There might be the case a tt_content FCE has no mapping, e.g. if an existing tt_content is
switched to type FCE, not setting a mapping and saving.
This patch changes the output template to show a warning message for that element to catch
that exception.

[BUGFIX] page module shows exception if a FCE has no mapping

---

Classes/Service/ItemsProcFunc.php
Configuration/TSConfig/Page.ts

This will allow easier supplying of sitepackages, as you can filter
mappings by page branch easily. Most template extension will provide
mappings as well as PageTSconfig, so with this you can easily do a
mod.web_txtemplavoilaplusLayout.filterMaps = vendor/yourextension
to not show other mappings in that branch. Thus allowing
multi-template-setups easily, while still retaining the access check
and thus allowing editors for different templates to not mix them up,
as we can now filter by page tree as well as user.
As there might be extension supplying FCEs only (e.g. bootstrap style
containers). there is an option to define an array of allowed stuff
like
mod.web_txtemplavoilaplusLayout.filterMaps.1 = vendor/yourextension/Page
mod.web_txtemplavoilaplusLayout.filterMaps.2 = …

[FEATURE] allow PageTSconfig option to filter for mappings

---

Classes/Configuration/FlexForm/DataStructureIdentifierHook.php

I called `vendor/bin/typo3cms referenceindex:update` and during that `DataStructureIdentifierHook::parseDataStructureByIdentifierPreProcess()` resolves the map of pages.
However in case of a deleted page the `dataStructure` retrieved is no `string` or `emptyString`, but just false, since the `queryBuilder` won't look up deleted pages (for good reason). However this `false` creates a `\TypeError` as `getConfiguration` expects a `string`. 
In order to not change any logic, but solve this problem this `TypeError` should just be handled like a normal `ConfigurationException`

[BUGFIX] unhandled type exception if deleted page needs map resolving during refindex update

---

Classes/Controller/Frontend/FrontendController.php

If the main page (uid 123) which defines the map has a subpage (uid 456) and uses
"content_from_pid" to point to that subpage the page cannot be rendered.
The record is the subpage record (456), the rootline is the mainPage rootline. However while
getting map from rootline the first element is skipped as it is the current page in most cases.
This patch removes that skipping, as it is barely slower and allows to identify the parent map
in a content_from_pid case.

[REGRESSION] content_from_pid can't resolve map in all cases

---

.github/workflows/ci.yml
composer.json

This is a WIP - for the time being it will just enable the CI tests for php 8 and 8.1 support and change the composer.json to allow those php versions, too.
This will be regularly rebased to reflect the changes to the codebase.

[TASK] allow php8

---

Classes/Controller/Frontend/FrontendController.php
Classes/Exception/ContentElementWithoutMapException.php

Currently "broken" tt_content elements (e.g. FCE without mapping) are just returned as emptyString to not break whole page output.
This patch adds the logging functionality marked as TODO and adds conditional output so that 
- on production systems still the current behaviour (no output) is done
- on non-production systems (FE debug enabled) the exception is thrown
Additionally the Exception for FCE without mapping is now named explicitly.

[TASK] Add conditional logging and exceptions for missing tt_content mapping

---

Classes/Controller/Frontend/FrontendController.php

While introducing the logger, this call wasn't done, thus omiting the typical AbstractPlugin init.

[REGRESSION] FEcontroller needs to call parent __construct

---

Classes/Handler/Mapping/DefaultMappingHandler.php

During the refactoring the REGISTERs `tx_templavoilaplus_pi1.parentRec.*` where re-introduced. However in old TVPv7 there was a  REGISTER `tx_templavoilaplus_pi1.current_field`, too.
As it doesn't create unnecessary load and this context information might help for output styling, it is re-introduced with this patch. The register holds the parent field (e.g. the page flex form field name, or the FCE flex form field name).

[REGRESSION] re-introduce the REGISTER tx_templavoilaplus_pi1.current_field

---

Classes/Controller/Frontend/FrontendController.php
Migrations/Code/ClassAliasMap.php
composer.json

During the switch to v8 the namespace changed, thus it is advised to change the TypoScript after the migration from
```
page.10.userFunc = Ppi\TemplaVoilaPlus\Controller\FrontendController->main_page
tt_content.menu.20.3.userFunc =  Ppi\TemplaVoilaPlus\Controller\SectionIndexController->mainAction
```
to
```
page.10.userFunc = Tvp\TemplaVoilaPlus\Controller\Frontend\FrontendController->renderPage
tt_content.menu.20.3.userFunc = Tvp\TemplaVoilaPlus\Controller\SectionIndexController->mainAction
```
However by introducing the deprecated function name `main_page` and let it call renderPage and also adding a class-alias-map, this can be made optional, thus resulting in an even easier migration.

[FEATURE] allow old TypoScript page userfunc

---

Classes/Handler/Mapping/DefaultMappingHandler.php

The PR https://github.com/T3Voila/templavoilaplus/pull/369 reintroduced the REGISTER `current_field`.
However the implementation was wrong as it just unsets the register after processing.
In case of e.g. a PAGE current_field `main_content` with flex form content elements, this leads to loosing the page current_field information as after the childs are processed it is unset.
Rather it needs to be reset to the value before starting the processing, to preserve the value.

[REGRESSION] current_field REGISTER unset from flexform childs

---

Classes/Controller/Backend/Ajax/ContentElements.php
Classes/Controller/Backend/ControlCenter/Update/AbstractUpdateController.php
Classes/Controller/Backend/ControlCenter/Update/DataStructureV11Controller.php
Classes/Controller/Backend/ControlCenter/Update/DataStructureV8Controller.php
Classes/Controller/Backend/PageLayoutController.php
Classes/Domain/Model/Configuration/TemplateConfiguration.php
Classes/Service/ApiService.php
Classes/Service/ProcessingService.php
Resources/Public/StyleSheet/PageLayout.css
Tests/Unit/Utility/ApiHelperUtilityTest.php
composer.json
phpstan-baseline.neon

Normal roundup. 
After another readup I found there is an option to have post-statement comments, but only if they are inline comments `/* */`, that allows the current behaviour - however single-line-comments `//` are forbidden after a statement.

Make CI tests green again

---

Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node/TypeInformation.html
Resources/Private/Partials/Backend/Preview/Tt_content/Bullets.html
Resources/Private/Partials/Backend/Preview/Tt_content/Elements/Header.html
Resources/Private/Partials/Backend/Preview/Tt_content/Elements/SubHeader.html
Resources/Private/Partials/Backend/Preview/Tt_content/Header.html
Resources/Private/Partials/Backend/Preview/Tt_content/Html.html
Resources/Private/Partials/Backend/Preview/Tt_content/Image.html
Resources/Private/Partials/Backend/Preview/Tt_content/Shortcut.html
Resources/Private/Partials/Backend/Preview/Tt_content/Text.html
Resources/Private/Partials/Backend/Preview/Tt_content/Textmedia.html
Resources/Private/Partials/Backend/Preview/Tt_content/Textpic.html

The currently used backend preview nodes could be slightly improvement, as my test system uses a lot of different kinds in combination which showed that stuff is a bit different, thus I propose:
- add shortcut tt_content preview, currently just showing the `table_uid` list
- always output header and subhead of tt_content (except for shortcut, html of course), thus put in their own partial. Header should respect header_layout=100 as hidden thus not showing it.
- ~the type is the first element in the preview, it should have the icon as a prefix to differentiate from field labels, else we would have, e.g.~
- the html tt_content preview should not show the interpreted HTML, but rather HTML code to prevent XSS and other shenanigans

Backend preview nodes improvement

---

Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node/ChildsBeLayouts.html
Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node/TypeInformation.html
Resources/Private/Partials/Backend/Preview/Tt_content/Default.html

The page module has two redundant labels:
1. On the top each node has a label of its type. For pages this is "Standard" as all other page types (e.g. Shortcut, Sysfolder) don't use a node view, thus this label can be removed.
2. On the bottom of each node there is a flex form fields preview. for pages with page areas, this just shows nothing, just the headings. As this at least for page areas is redundant and not helpful, it will now just conditionally output if there is something to display.

Page module: remove redundant labels

---

Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node/TitleBar.html
Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node/TitleBarLeftButtons.html
Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node/TitleBarRightButtons.html
Resources/Public/StyleSheet/PageLayout.css

Currently the title was hard-cropped at 20chars; however CSS allows for soft-cropping. This would even allow to mouse-over for full title.

[TASK] node titlebar should crop title via CSS and shouldn't wrap

---

Resources/Private/Language/Backend/PageLayout.xlf
Resources/Private/Templates/Backend/Ajax/ContentElements.html
Resources/Public/StyleSheet/PageLayout.css

The new ContentElement Wizard  currently has low UX discoverability. In order to improve the transition for editors it should be made clearer how it works.
So this proposes two changes:
a) The first tab (in most cases probably standard content elements) should be active initially
b) There should be a heading "add new content element" as well as a description, that one needs to use drag and drop instead of click as previously

New ContentElement Wizard improvements

---

Resources/Private/Templates/Backend/Ajax/ContentElements.html

cewizard uses different tab active items as 11LTS thus some new IFs are in place to put the `active` class at the right spot

[REGRESSION] activate first cewizard tab in pre-11LTS 

---

Classes/Controller/Backend/PageLayoutController.php

- editors which just login only see an exception if no page is selected in backend tree, because pageinfo is false
- the calcperm call for non-admins is missing parameters, thus always returning false, thus disabling the newCE sidebar button

[BUGFIX] non-admins can't add content

---

Classes/Handler/Render/XpathRenderHandler.php

Using ddev 1.21.1 with php 7.4 my working config shows up broken. Multiple wraps are missing or the label `__TEMPLAVOILAPLUS__>` is output. This points to XpathRenderHandler::processValue*().
Replacing the tag with just lower case ascii immediatly solved the problem. Seems a hiccup in an XML lib, because according to XML spec underscore is perfectly fine. But this will make it a bit more robust

[BUGFIX] ddev breaks processValue wraps

---

Resources/Private/Templates/Backend/PageLayout/Show.html
Resources/Public/JavaScript/PageLayout.js

currently `settings.configuration` was output as json. That included the full TCA. this attribute slowed down page rendering in general and developer console for quick CSS fixes too.
as `settings.configuration.tca` is used in fluid this must stay; as the javascript only accesses userSettings, I propose to just output usersettings. 
Especially in Safari this is a major performance boost

[TASK] json settings output should be userSettings only

---

Classes/Domain/Repository/PageRepository.php

[BUGFIX] PageRepository was moved to cms-core in 10LTS, not 9LTS

---

Resources/Public/JavaScript/PageLayout.js

For short content headers just a string is used, however long content headers have <h1><span title="fulltitle">croppedtitle</span></h1> Thus in order to copy this to the modal title html needs to be used instead of text.
fixes #433

[BUGFIX] content edit modal title should accept HTML

---

Classes/Service/ProcessingService.php

Due to an error in a custom new content element wizard I created FCEs without a mapping set, this broke the page module with an exception:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 5 passed to Tvp\TemplaVoilaPlus\Service\ProcessingService::getNodeChildsFromElements() must be of the type array, null given, called in typo3conf/ext/templavoilaplus/Classes/Service/ProcessingService.php on line 329`
While it could be catched beforehand, this is actually the only thing that will raise an excetion in case of such broken CEs, so I propose an easy fix via IF.

[BUGFIX] FCEs with no mapping create exception

---

Classes/Controller/Backend/PageLayoutController.php
Classes/Domain/Repository/PageRepository.php
Classes/Utility/IconUtility.php

This PR covers two small changes to the page info flash messages on top in cases of "shortcut", "content_from_pid" and "content_on_pid". The code is checked for backwards compatibility, in both cases 11LTS, 10LTS and 9LTS behave the same, however the adaptions would be hard for 8LTS, so for 8LTS the behaviour is not adapted.
The icon is page.type but not the TYPO3 core calculated icon, which could be different (e.g. using page.module for custom icons or being a site root); this should be the calculated icon.
E.g. in case from content_from_pid a info is shown like This content is also shown on: Startseite [26197], Home [33757]
However the entry HOME should not be mentioned, as it is a translation of STARTSEITE and has content_from_pid set to "value of default language"

[TASK] page info flash messages have redundant entries and wrong icon

---

Classes/Service/ProcessingService.php
Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node.html

FCEs with no mapping offer no drop area obviously and the error message is just black in the preview area. Instead the same node-information-style like with "used multiple times on this page" should be used to be more coherent and make it more visible.

[TASK] FCEs with no mapping error should be more visible

---

Classes/Service/ProcessingService.php

Child nodes are retrieved and added to an array via a key <table>:<uid>
However this prevents the same content from being added to a container multiple times, so currently a FCE container that has the same CE 2 times will only show one element in the backend. As the view is out of sync with the flex field adding/moving/etc elements into and out of that container will create race conditions.
As the key is not used anywhere, it is dropped in favor of basic numbering

[BUGFIX] if node has same children multiple times it is not shown

---

Classes/Handler/Configuration/MappingConfigurationHandler.php

As the name of the MappingConfiguration is exposed to editors, it makes sense to make this localizable for their own language. So the MappingConfiguration.yml:meta:name should allow for `LLL:` strings
While it would be possible for the other *Configurations as well, they are only exposed to admins, thus fixed labels are sufficient.

[FEATURE] MappingConfiguration should allow LLL-names

---

Classes/Handler/Mapping/DefaultMappingHandler.php

Instead of parsing the child nodes it could be relevant to just output the whole row, especially for the fluid renderer this would allow nested fluid templates, instead of rendering the childs and copying the result into the main fluid template.

[FEATURE] new mapping type RowList

---

Classes/Utility/IconUtility.php

In seldom conditions the original code is not robust enough. E.g. a page of type shortcut which had an content_from_pid set to a non existing page an exception would be raised, which would disable the whole page module for that page.

[BUGFIX] Argument 2 passed to IconUtility::mapRecordTypeToIconIdentifier() must be of the type array, null given

---

Classes/Service/ProcessingService.php
Documentation/CreatingTemplateExtension/PageUserTsconfigReference/Index.rst
Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node.html

It would be a benefit if like in TVP7 column values of nodes could have an inpact in BE preview rendering. In TVP7 this was hardcoded to `tt_content.layout` I propose to re-implement it and make it TSconfig configurable, e.g. use
`mod.web_txtemplavoilaplusLayout.additionalRecordData.tt_content = layout,imageorient`
to add `data-layout` and `data-imageorient` to a `tt_content` node in order to allow further custom CSS styling or custom JavaScript beyond the option for BackendLayouts.

[FEATURE] add TSconfig additionalRecordData.<table> for BE node data attributes

---

Classes/Controller/Backend/Ajax/ExtendedNewContentElementController.php
Classes/Hooks/WizardItems.php
Classes/Service/ItemsProcFunc.php

#339 introduce map filtering, that was respected in TCA/TCEForm quite fine, but the newCeWizard tab FCE doesn't respect it. Additionally the old option to use
`mod.wizards.newContentElement.wizardItems.fce.show = *` or
`mod.wizards.newContentElement.wizardItems.fce.show = fce_<identifierA>,fce_<identifierB>` was missing to slim the entries in the tab to have any control on this.
This would again allow to hide the tab completely, e.g. via
`mod.wizards.newContentElement.wizardItems.fce.show = none` (as 'none' is a non-existing element) in order to use custom wizards on your own

[BUGFIX] filterMaps and pageTSconfig wasn't respected in NewCeWizard

---

Classes/Controller/Backend/Ajax/Clipboard.php
Classes/Exception/ProcessingException.php
Classes/Service/ProcessingService.php
Resources/Private/Templates/Backend/PageLayout/Show.html
Resources/Public/JavaScript/PageLayout.js

While working on #453 I stumbled over errors being just returned as "400: false". 
I propose adding TYPO3 Notification api (available since 8LTS) to have instant-flashmessages in the top right corner, which allow to show an error message instead of silently failing in the browser console.
(Screenshot with bad spelling, fixed later, forgot to make new screenshot)
This should probably be helpful for all ajax actions, but I rather wanted to propose this first before rehauling everything.

[TASK] add notification API and provide meaningful error messages (for clipboard actions)

---

Classes/Controller/Backend/Ajax/AbstractResponse.php
Classes/Controller/Backend/Ajax/ContentElements.php
Resources/Public/JavaScript/PageLayout.js

adding a new FCE doesn't activate its dropzone, as the ajax-provided HTML code is showing a wrong data-parent-pointer and because the javascript events aren't registered
Addition, see https://github.com/T3Voila/templavoilaplus/pull/455#issuecomment-1281954544: clipboard wasn't working either on new nodes

[BUGFIX] newly added Nodes are missing handlers

---

Classes/Service/ProcessingService.php

destinationPointer is deemed invalid because empty, thus allowNew needs to be true

[BUGFIX] clipboard copy to empty area broken

---

Classes/Controller/Backend/Handler/DoktypeLinkHandler.php

fixes #446
In contrast to the other page types here is no button as buttons won't work with external URLs (no option for target _BLANK, X-Frame-Options prohibiting it in general.
The link can't be added to the FlashMessage either, as that doesn't allow HTML code.
Thus the URL is only shown in text as ist without a way to click it.

[BUGFIX] page type external shows exception in BE page module

---

Classes/Service/ProcessingService.php

codequality checks showed a wrong casing in var name for `moveElement`

[BUGFIX] case problem with variable name

---

Classes/Controller/Backend/PageLayoutController.php
Classes/Utility/TemplaVoilaUtility.php

In order to cope for different l10n stuff it is important to sum up all info. This function provides a pseudo `languageAspect`, which is the core way to know the correct fallback for the currently selected language. As we focus on a single page additionally `pages.l18n_cfg` is added which can change the language mode per page. As this can create a lot of combinations, this introduction of an adapted `languageAspect` could work as single point of complexity.
This is to support functions for language views (e.g. only show translation with id 2 and not all) and could be either used
* while doing the output in fluid to simply filter the view, or
* while actually fetching localizations and localizationActions thus adding to the `sDEF`/`vDEF` complexity (which would be possible, but probably …

[FEATURE] introduce languageAspect and pages.l18n_cfg information to settings

---

Classes/Hooks/WizardItems.php

the newCEwizard hook expects ExtendedNewContentElementController to retrieve the page. This works if newCEwizard is called inside TVP, but not if its called in list module.
For the sake of not having a better fix, the whole filtering of FCEs is disabled in list module to prevent an exception up until a better fix is available.
exception for reference:
```
Tue, 25 Oct 2022 18:02:36 +0200 [CRITICAL] request="1b357f0bd48b5" 
component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": 
Core: Exception handler (WEB: BE): Error, code #0, 
file /typo3conf/ext/templavoilaplus/Classes/Hooks/WizardItems.php, line 46: 
Call to undefined method TYPO3\CMS\Backend\Controller\ContentElement\NewContentElementController::getPageId()
```

[BUGFIX] newCEwizard hook expects ExtendedNewContentElementController

---

Classes/ViewHelpers/ToolTipAttributesViewHelper.php
Resources/Private/Language/Backend/PageLayout.xlf
Resources/Private/Templates/Backend/PageLayout/Show.html
Resources/Public/JavaScript/PageLayout.js

Bugfix: before the icon "clipboard" and "trash" could be dragged out of their sidebar nav item.
Addon: now we have bootstrap tooltips for the sidebar items to improve UX: a lot of editors asked how to delete stuff, thus a mouseover-info for the delete icon might help.
Added a tooltip helper which creates attributes based on TYPO3 version which can reduce number of condition in other partials, too.

[TASK] sidebar buttons need tooltip, icons shouldn't be draggable

---

Classes/Handler/Mapping/DefaultMappingHandler.php
Classes/Handler/Render/XpathRenderHandler.php

An FCE with a Mapping of
```
field_heading:
valueProcessing: typoScript
valueProcessing.typoScript: |-
10 = TEXT
10.data = register:tx_templavoilaplus_pi1.parentRec.header
```
throws exceptions as `dataType` and `valueType` are undefined

[BUGFIX] PHP8.1 optimization: valueProcessing typoScript throws exception

---

Classes/Controller/Backend/Ajax/ContentElements.php
Classes/Service/ProcessingService.php

Got an install where due to a switch to utf8mb4 creating a tt_content threw an SQL exception, however TVP died silently.
This adds exception handling for insertElement, as done already for other stuff to show the exception in the error flash message

[TASK] add exception handling for insertElement

---

Classes/Controller/Backend/LinkBrowserController.php
Configuration/Backend/Routes.php

fixes #502
overwrite TYPO3\CMS\Backend\Controller\LinkBrowserController::initDocumentTemplate and add a requireJS configuration for mapping FormEngineLinkBrowserAdapter
This modification should be load this new code only for typo3 version < 11.
However, i tested it only for typo3 v. 10.
I didn't test it with typo3 version 11 or more, but it should work.

[BUGFIX] fixes #502

---

Classes/Utility/TemplaVoilaUtility.php

Deprecation-94414 says use LanguageServiceFactory if no $GLOBALS['LANG']
compatible with 11LTS/12LTS, so probably no back port

[BUGFIX] Too few arguments to function LanguageService::__construct()

---

Classes/Controller/Backend/LinkBrowserController.php
Classes/Core/Page/JavaScriptModuleInstruction.php
Resources/Public/JavaScript/ParentWindow.js
ext_localconf.php

Didn't test myself in pre-11, but the code is quite clear. The new solution resolves regressions with the LinkBrowser if the later is used e.g. in list module (changes were not transferred, same error TVP page module had, so we just traded one problem for another).
As requested in https://github.com/T3Voila/templavoilaplus/pull/510#pullrequestreview-1553649759:
Providing new variant for >=11 and retaining old solution for <=10
fixes #510, fixes #502, rels #503, rels #507, rels #508
backport 8.1.x

[FEATURE] refactor LinkBrowserController fix from #510

---

composer.json
phpstan-baseline.neon

This patch removes one unmatched error pattern,
which seems to be fixed meanwhile.
In addition, the composer script for generating
the baseline has an added "--level 0" option so
that it aligns with the CI pipeline.

[TASK] Update phpstan-baseline.neon

---

Classes/Handler/Render/XpathRenderHandler.php

RenderHandlerInterface::renderTemplate() doesn't have $request in 8.2.x, was added in main.
Adding it now would break EXT:tvplus-fluid. As $request is not used anyways yet, just dropping it.

[REGRESSION] method signature mismatch

---

Classes/Configuration/FlexForm/FlexFormTools8.php

During 12LTS migration an EXT:cal upgrade wizard failed because FlexFormTools8::cleanFlexFormXML_callBackFunction() created an exception.
After applying the migration path from https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.5/Deprecation-95254-TwoFlexFormToolsMethods.html to fix that exception the further calls relied on an `$pObj->traverseFlexFormXMLData_Data` which I couldn't resolve to anything. So probably as of time of writing this was always null and probably thus nothing much was done in that `if`. The remainder of the function is from the base function, so I propose to just delete it.
While that resolves my updater issues, I don't have enough insight to prove that there are no race conditions from this, so please check this
¯\\\_(ツ)\_/¯

Fix FlexFormTools callbackFunction

---

.github/workflows/ci.yml
Classes/Controller/Frontend/PageBasicsHandler.php
Classes/Service/DataHandling/DataHandler.php

PHP 8.4 tests would need a revamp of the dependencies, so skipped for now

Test Optimization: fix 2 sniffs and add PHP 8.3 tests
